---

- name: Update apt
  apt: update_cache=yes
  become: true
  become_user: root
  become_method: sudo

- name: Upgrade all safe packages
  become: true
  become_user: root
  become_method: sudo
  apt: upgrade=safe

# Install basic Stuff
- name: Install zip, unzip, git
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "{{ basics }}"
  vars:
    basics:
      - zip
      - unzip
      - git

- name: Install openjdk
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "openjdk-11-jdk"
  when: ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 10

- name: Install openjdk
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "openjdk-8-jdk"
  when: ansible_distribution != 'Debian' or ansible_lsb.major_release|int < 10

- name: add packages.sury.org/php public_key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
  when: ansible_distribution == 'Debian'

- name: php - add repository
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ {{ansible_distribution_release}} main'
    filename: php
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: php - install base packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
      - "php7.0"
      - "php7.0-gd"
      - "php7.0-xml"
      - "php7.0-mysql"
      - "php7.0-mbstring"
      - "php7.0-soap"
  when: ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 10

- name: Install php
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php
      - php-gd
      - php-xml
      - php-mysql
      - php-mbstring
      - php-soap
  when: ansible_distribution != 'Debian' or ansible_lsb.major_release|int < 10

- name: install apache2
  become: yes
  apt:
    name: apache2
    state: latest

- name: Install mariadb
  become: yes
  apt:
    name: "{{ dbpack }}"
  vars:
    dbpack:
      - mariadb-server
      - python-mysqldb
