---

#create database und tables

- name: Set MariaDB useer password for the first time
  become: yes
  become_user: root
  mysql_user:
    name: ilias
    password: 12345678
    priv: '*.*:ALL,GRANT'
    state: present

